/* eslint-disable global-require */
export const AppImages = {
    img_logo: require('./logo.png'),
    img_background: require('./background.png'),
    img_bg_register: require('./background_register.png'),
    img_fb: require('./Facebook.png'),
    img_apple: require('./apple.png'),
    img_google: require('./google.png'),
    img_avt: require('./avt.jpg'),
    img_ball: require('./futbol.png'),
    img_gk: require('./gk.jpg'),
    img_albania: require('./albania.png'),
    img_israel: require('./israel.png'),
    img_iceland: require('./iceland.jpg'),
    img_avt_player: require('./avt_player.jpg'),
    img_ticket_yellow: require('./ticket.png'),
    img_ticket_red: require('./ticket_red.png'),
    img_goal: require('./ball.png'),
    img_replace: require('./arrow-right-arrow-left.png'),
    img_club: require('./club.png'),
    img_coach: require('./hazan.jpg'),
    img_leagues: require('./leagues.png'),
    img_gallery: require('./gallery.png'),
    img_club_fav: require('./Ma_Tel_Aviv.png'),
    img_thumbnail: require('./neymar.jpg'),
    img_cup: require('./cup.jpg'),
    img_state_cup: require('./state_cup.png'),
};
